### ISSUE TITLE
KeyError: 'camera' error

### ISSUE THREAD

**Issue by official-akshayjadhav** [visualbuffer/parkingslot#10]
getting KeyError: 'camera' while executing  resnet_occupancy.py file

@visualbuffer can you help me to solve this?

complete error log:
Traceback (most recent call last):
  File "C:\Users\5tg_user1\AppData\Local\Programs\Python\Python38\lib\site-packages\pandas\core\indexes\base.py", line 3080, in get_loc
    return self._engine.get_loc(casted_key)
  File "pandas\_libs\index.pyx", line 70, in pandas._libs.index.IndexEngine.get_loc
  File "pandas\_libs\index.pyx", line 101, in pandas._libs.index.IndexEngine.get_loc
  File "pandas\_libs\hashtable_class_helper.pxi", line 4554, in pandas._libs.hashtable.PyObjectHashTable.get_item
  File "pandas\_libs\hashtable_class_helper.pxi", line 4562, in pandas._libs.hashtable.PyObjectHashTable.get_item
KeyError: 'camera'

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "Parking_Slot_mask_rcnn.py", line 233, in <module>
    image_data =  get_data()
  File "C:\Users\5tg_user1\Desktop\proj-ml-parking-lot-occupancy-detection\5tg_ml_parking_lot_occupancy-detection\utilities.py", line 81, in get_data
    image_data["camera"] = image_data["camera"].astype("category")
  File "C:\Users\5tg_user1\AppData\Local\Programs\Python\Python38\lib\site-packages\pandas\core\frame.py", line 3024, in __getitem__
    indexer = self.columns.get_loc(key)
  File "C:\Users\5tg_user1\AppData\Local\Programs\Python\Python38\lib\site-packages\pandas\core\indexes\base.py", line 3082, in get_loc
    raise KeyError(key) from err
KeyError: 'camera'

**Comment by PrasadShete20** [comment]
@official-akshayjadhav have u found any other repo related to , parking slot detection which is running fine??
